baseURL: https://elizabethoneitadavis.netlify.app
languageCode: en-US
title: Elizabeth Oneita Davis
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Elizabeth Oneita Davis
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Describe your website
  social:
    Email: edavis@sdzwa.org
    Twitter: username
menu:
  main:
    - identifier: blog
      name: publications
      url: /publications/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300
